### ISSUE TITLE
ConEmuC: Root process was alive less than 10 sec, ExitCode=0. Press Enter or Esc to close console...

### ISSUE THREAD

**Issue by hamzahamidi** [cmderdev/cmder#2024]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 

I have the following issue whenever I run cmder. I tried reinstalling it but I still have the same issue.

```
ConEmuC: Root process was alive less than 10 sec, ExitCode=0. 
Press Enter or Esc to close console...

**Comment by hamzahamidi** [comment]
Never-mind, I fixed my issue. 
```
Run regedit 
Go to HKLM\Software\Microsoft\Command Processor\ or HKEY_CURRENT_USER\Software\Microsoft\Command Processor\ or HKEY_LOCAL_MACHINE\Software\Microsoft\Command Processor\

For some reason there was AUTORUN key with "EXIT" inside.

Remove the AutoRun key and everything should went back to normal.
```
cmder should work again.

**Comment by Tapudp** [comment]
I don't have any AUTORUN key in there and the CMDer still not working. Is there any other alternative around?

**Comment by freeideas** [comment]
in my HKCU (etc) \Command Processor\ registry folder, it said AUTORUN = "if exist"
I deleted that, and both cmder and Hyper started working again. WTF is that registry value? Wow.

**Comment by chrisant996** [comment]
> HKCU (etc) \Command Processor\ ... AUTORUN
> ... WTF is that registry value?

It's a documented registry key that on startup of cmd.exe automatically runs whatever command is set in the registry key.

An internet search for "command processor autorun" will find more information about it.

Sounds like something set it and maybe messed up how it was setting it, leaving a broken partial command in the registry key.
