### ISSUE TITLE
{git}, {lamb} and strange new console options

### ISSUE THREAD

**Issue by ashecorven** [cmderdev/cmder#223]
Fresh download of mini or full version 1.1.3, opening cmder.exe results in {git} and {lamb} in prompt.

![image](https://cloud.githubusercontent.com/assets/8173636/3591611/1f8db45a-0c66-11e4-8e65-f372f07a52ba.png)

As per similar issues resolution- https://github.com/bliker/cmder/issues/126
Attempting to remove clink from global autorun
![image](https://cloud.githubusercontent.com/assets/8173636/3604398/cb1209c0-0d1f-11e4-95ae-b0b6098677a0.png)
Doesn't have an effect that I can see.

Also new console window has some strange options 
![image](https://cloud.githubusercontent.com/assets/8173636/3591619/36e661f6-0c66-11e4-9ffb-58ecaa58cd39.png)

This is my first time attempting to use cmder, have never had clink installed before.

Also the installation instructions on the homepage reference cmder.bat, which is not contained in the v1.1.3 archives.

**Comment by leviwilson** [comment]
I'm having the same issue and I do not have AV installed.

```
Clink v0.4.3 [git:258fc3] Copyright (c) 2014 Martin Ridgers                         
http://mridgers.github.io/clink                                                     
                                                                                    
                                                                                    
C:\Users\lwilson {git}                                                              
{lamb} clink                                                                        
Clink v0.4.3 [git:258fc3] Copyright (c) 2014 Martin Ridgers                         
http://mridgers.github.io/clink                                                     
                                                                                    
Usage: <verb> <verb_options>                                                        
                                                                                    
  Verbs:                                                                            
  inject   Injects Clink into a process.                                            
  autorun  Manage Clink's entry in cmd.exe's autorun.                               
  set      Adjust Clink's settings.                                                 
           ('<verb> --help' for more details).                                      
                                                                                    
                                                                                    
C:\Users\lwilson {git}                                                              
{lamb}                                                                              
```

**Comment by gosukiwi** [comment]
What OS are you using? For windows 10 you'll need [a newer version of clink](https://github.com/mridgers/clink/issues/253)

**Comment by leviwilson** [comment]
Oh yes, sorry about that: Windows 7

**Comment by JoshSchreuder** [comment]
@leviwilson 
I had this issue after installing v0.4.3 off the Clink website - I needed to copy the files from Program Files into cmder's vendor folder, then uninstall it from Program Files, then it was back to normal.

Guess there's a clash if it's installed in Program Files & cmder at the same time.

**Comment by leviwilson** [comment]
Hmm, I have it in multiple spots (probably from installing ConEmu prior to finding Cmder?)
![screen shot 2015-02-17 at 1 52 15 pm](https://cloud.githubusercontent.com/assets/574434/6234898/428c5ba0-b6ac-11e4-8f22-5f5b49c4709e.png)

**Comment by keradus** [comment]
fresh install on Win10 using Chocolatey, same issue here

**Comment by srimajji** [comment]
@keradus fix for win10 is here. https://github.com/mridgers/clink/issues/253 
just update clink files that's in /cmder/vendor/clink

**Comment by keradus** [comment]
Thank you @srimajji !  It works for me ;)

**Comment by meeglos** [comment]
In my case, when updating displayed the {git}, {lamb} cursors, by the way my firewall and antivirus were disbled, now I just enabled both and everything turned just fine, the issue was fixed.

**Comment by InvDeath** [comment]
win 8.1 and win 10 with {git}, {lamb}. I didn't install any antiviruses (only with os)

**Comment by atantillo** [comment]
I solved this issue recently, so hopefully your experiences are similar to mine. 

Just to note, I am using Windows 10 Pro Technical Privew. 

I had identical copies of clink, both version 0.4.4, in two locations; program files and Cmder. I uninstalled the one in the program files location, and voila, my beautiful λ came back to me. 

I'm sure removing the extra clink's global variable should be sufficient, but I just got rid of the whole thing. 

Good luck!

**Comment by brunowego** [comment]
+1

**Comment by torresandres** [comment]
Hi everyone, i solved this issue in Win7 following this simple steps:

* Closing ConEmu.
* Download latest portable version of clink (0.4.4 at the time).
* Update clink manualy extracting files to  `<cmder>/vendor/clink`.
* Starting cmder.

**Comment by shreejay** [comment]
@torresandres . Thanks! This solution worked for me. 
OS: Windows 8.1 
Same issue as the first post mentioned. {git}, {lamb}. Started seeing this after the install of Bitdefender Total Security 2015. Tried adding CMDer and ConEmu exe files into excluded list. But did not help.

**Comment by r03** [comment]
The solution from @torresandres worked for me too. (Win8.1 with bitdefender)

**Comment by cooper6581** [comment]
I was able to solve this issue on Win7 by removing my system installation of clink. Even when clink 0.4.4 was installed, the lambda prompt didn't start working until I removed my system installation.

**Comment by Jayflux** [comment]
@cooper6581  I will give this a try later

**Comment by alexeygrant** [comment]
@torresandres solution has worked for me (Windows 8.1, BitDefender)

**Comment by ch1na-d0ll** [comment]
@torresandres solution worked for me also. (Windows 7, BitDefender Antivirus free edition)

**Comment by ashecorven** [comment]
@torresandres solution works for non-admin consoles only. Admin still has same symptoms.

**Comment by alexeygrant** [comment]
Hmm, I've just double-checked and can confirm that the @torresandres solution worked for both non-admin and admin consoles.

**Comment by jpmn** [comment]
@torresandres solution worked for me also on Windows 10 Pro.

**Comment by jaffarc** [comment]
Problem windows 10 
C:\Users\Usuario {git}
{lamb}

removing {git}
{lamb} ??

**Comment by indranilsinharoy** [comment]
I faced the same problem after upgrading to Windows 10. The solution provided by @torresandres worked for me.

**Comment by BrunoMoreno** [comment]
Just use the new version of Clink:
https://github.com/mridgers/clink/releases/tag/0.4.3

**Comment by BrunoMoreno** [comment]
Now works fine:
I made a remaster running on Windows 10

**Comment by JimMorrison723** [comment]
+1 @torresandres: thanks, it works now correctly.

**Comment by keradus** [comment]
btw, error reported in July 201**4**, can't fix be released and issue closed?

**Comment by andreibenhur** [comment]
+1 @torresandres: it works for me too

**Comment by pascalz** [comment]
@torresandres . Thanks ! Working for me. 
OS: Windows 10

**Comment by mike-alexander** [comment]
Just replacing all the files in vendor/clink with the latest clink version fixed it for me. Thanks @torresandres.

**Comment by vmuriart** [comment]
Removing system install of Clink solved it for me.

**Comment by Lissy93** [comment]
Thanks @torresandres  and @mike-alexander 
Fixed it for me when I deleted the contents of cmder/vendor/clink then replaced it with Clink v. 0.4.3 (https://github.com/mridgers/clink/releases/tag/0.4.3) it works great on Windows 10

**Comment by t5k6** [comment]
If you still have a problem check this thread:
https://github.com/Maximus5/ConEmu/issues/270
Apparently there is an incompatibility of hooking methods between latest versions of ConEmu and Clink.

**Comment by psgganesh** [comment]
@torresandres that worked ;) perfect :100: :+1: Step 1 is very important before anything, Thank you once again :)

**Comment by johnkors** [comment]
@torresandres 's solution also works here. Win 8.1, BitCommander and cmder installed via Chocolatey.

**Comment by Jayflux** [comment]
yep @torresandres worked
Can we not just update it from here, is there a PR for this?

**Comment by Stanzilla** [comment]
@Jayflux our latest pre release comes with the latest clink release, that's why.

**Comment by Jayflux** [comment]
@Stanzilla  are you sure?
I downloaded 1.2.9 which looks like your latest release and still had this problem

**Comment by Stanzilla** [comment]
@Jayflux nope, should be in 1.2.9, please make sure you delete any older files you have there before you copy the new ones in, especially the lua files have changed and having some there twice could break it.

**Comment by navkor** [comment]
yep @torresandres worked Windows 10 clean install.  But you have to remove the contents of the clink vendor directory first.  Then, make sure it isn't installed in programs.  Then, just for good measure, I tried to run it in the Cmd just to see.  And then, I extracted the zip contents into the vendor/clink folder.  Then it works.  It was so awesome to see!  Finally!

**Comment by kruncher** [comment]
I just had the same issue after having accepted the automatic update prompt. I was able to resolve this by downloading the latest portable version of clink and the overwriting the one inside the cmder directory.

**Comment by Gonnagle** [comment]
Like @kruncher I also just suffered the same problem when I let cmder autoupdate itself. Fixed with @torresandres solution.

OS: Windows 8.1 Enterprise (64-bit)

**Comment by Deathnerd** [comment]
I let Cmder autoupdate today and came across this issue. I've tried @torresandres solution but to no avail. I've also disabled any AV I have running and still no change. Running Windows 10 Pro 64-bit.
![capture](https://cloud.githubusercontent.com/assets/1685953/15933887/8699f630-2e2f-11e6-8fc5-f65d3712ec1e.PNG)

**Comment by Deathnerd** [comment]
Nevermind. I had two installations of cmder for some reason and applied the fix to the wrong one. All hail cmder and @torresandres!

**Comment by mystrdat** [comment]
Manually updating clink in the `/vendor` folder worked for me.

**Comment by adambotley** [comment]
+1 @mystrdat 

> Manually updating clink in the /vendor folder worked for me.

this solved the problem for me too

**Comment by barabator** [comment]
@torresandres Thank you for solution!

**Comment by rakete** [comment]
I just wanted to mention that it is possible to use cmder with its own clink and still have the functionality where clink injects itself into every cmd as if it was installed globally.

When clink is installed globally it creates two keys in the registry:

    HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Command Processor\AutoRun
    HKEY_CURRENT_USER\SOFTWARE\Microsoft\Command Processor\AutoRun

with a string pointing to the clink.bat file that should be something like:

    C:\Program Files\cmder\vendor\clink\clink.bat

so that every time a cmd is opened, that clink.bat file is executed and injects clink. Now, I assume cmder prefers to run clink itself, and the problems discussed in this issue stem from having the globally installed clink inject itself into cmder before it can inject clink on its own. So, to get clink to inject into every cmd and have cmder still work correctly, all that needs to be done is to exclude cmder when automatically injecting clink.

To do that it is possible to check if the CMDER_ROOT variable is defined and then not inject clink if it is. You can probably just edit the clink.bat, but I choose to create my own bat with something like this:

    @echo off
    if not defined CMDER_ROOT (
        "c:\Program Files\cmder\vendor\clink\clink_x64.exe" inject --quiet --profile "c:\Program Files\cmder\vendor\clink\profile"
    )

and then put that into the AutoRun registry keys. This should give clink injected into every cmd that is not cmder, like ConEmu or just plain cmd.exe, and still have cmder work correctly with clink.

**Comment by romaindurand** [comment]
@torresandres 's solution worked for me !

**Comment by Jayflux** [comment]
Can people please use the +1's on the bottom of the comments, its a bit annoying getting pinged about this thread for "me too" comments

Thanks!

**Comment by valuka** [comment]
@torresandres 's solution worked for me too.

Hopefully with next Cmder update I wont have to install Clink manually again.

**Comment by chriswithpants** [comment]
Direct link to save people hunting for that solution:
https://github.com/cmderdev/cmder/issues/223#issuecomment-90946902

Cheers @torresandres, worked for me too.

**Comment by shrayasr** [comment]
Got an update yesterday that pushed my ConEmu up to `160619 stable` and started seeing the same issue. 

[@torresandres' fix](https://github.com/cmderdev/cmder/issues/223#issuecomment-90946902) worked fine for me. Clink is now at version 0.4.7

**Comment by vmuriart** [comment]
@rakete 's idea worked for me. I implemented it on `clink.bat` directly instead.

**Comment by veirus** [comment]
Super Easy Fix -- insert this into your "C:\Program Files (x86)\clink\0.4.8\clink.bat" :
`if defined CMDER_ROOT goto :eof`

The downside is that modifying anything inside `Program Files` dir require admin rights.

**Comment by LordHog** [comment]
Wanted to say that @torresandres solution also worked for me
