### ISSUE TITLE
\\Git\\cmd\\ was unexpected at this time

### ISSUE THREAD

**Issue by ildoc** [cmderdev/cmder#2250]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
cmder v. 1.3.14.982 on win10

### Description of the issue
I've just installed cmder through chocolately, and at every startup I get this message 

![ConEmu64_Tsxeq7W1uf](https://user-images.githubusercontent.com/1956565/72742437-9f809900-3ba1-11ea-9b86-85a33475acb1.png)

also, linux commands don't work

![ConEmu64_WwALRlbs06](https://user-images.githubusercontent.com/1956565/72742221-2bde8c00-3ba1-11ea-9c3d-8630ea6efaab.png)

I also tried using the zip downloaded from the website and the one downloaded from the release section, but I got the same issue every time

**Comment by daxgames** [comment]
@ildoc output of `where git`?

**Comment by daxgames** [comment]
@ildoc See #2220

**Comment by daxgames** [comment]
@ildoc we will close this issue if you don't respond. We can't help without more information.

**Comment by Stallind** [comment]
I got the same error, I posted in the linked issue.

Here's what I wrote.

![image](https://user-images.githubusercontent.com/43113499/76756728-90bff800-6786-11ea-8e74-3001d2fe113b.png)

**Comment by daxgames** [comment]
@Stallind what version of cmder?  Have you tried [this](https://ci.appveyor.com/project/MartiUK/cmder/build/artifacts).

**Comment by Stallind** [comment]
@daxgames the one from appveyor is the one I'm using, tried both cmder_mini and full cmder.
It seems to be working as intented though. I can use my git. I don't know if any functionallity is missing or if it's just an annyoing startup message I keep getting

**Comment by daxgames** [comment]
@Stallind The only thing I see that MAY be causing it and it is a guess, is that you have 32Bit Git installed on 64Bit windows and maybe the `init.bat` script has an issue with the `(x86)` in the path to `git.exe`.  I have 64Bit git on my system and do not have your issues.

Uninstall the Git you have and reinstall 64Bit Git from [here](https://git-scm.com/download/win).  It should install to `C:\Program Files\Git` instead of ``C:\Program Files (x86)\Git`

**Comment by daxgames** [comment]
@Stallind Thats not it.  I just uninstalled my 64Bit and installed 32Bit and no issues.

**Comment by Stallind** [comment]
@daxgames i installed the 64-bit git and I no longer get the error message

**Comment by daxgames** [comment]
@Stallind Thats odd, I did the exact opossite and uninstalled 64Bit and installed 32Bit and had no change and still no error.

**Comment by Stallind** [comment]
Very weird, I never had the problem before running 32bit. 
Now I had to reinstall everything because I formatted and I just put all the programs install path to what was suggested. 

Anyway, seems to have solved it. Could be some kind of write/read permission on the different program folders. (That's by default) 

Thanks for the help.

**Comment by daxgames** [comment]
Should be fixed in latest master branch [here](https://ci.appveyor.com/project/MartiUK/cmder/build/artifacts)

**Comment by WimSubzero** [comment]
Hi daxgames,

just installed the latest master branch, sorry but still having this issue 
I do not have Git-for-windows installed, I just unpacked the zip as I did before.

by the way cmder ... greath stuff !

Wim

**Comment by daxgames** [comment]
@WimSubzero Cmder mini or Cmder?  No one has reported this with the latest master builds so this is very odd.

**Comment by vazapully** [comment]
I had this issue on 1.0.995-master
Where in the path variables were getting printed with the line "was not expected at this time"
I looked into my PATH variables and found in my Windows10 env, one path entry had two entries separated by a semi colon, I moved them to different entries and the issue has now gone away.

**Comment by CosmicRayHit** [comment]
I was having the same issue. For me when I moved my Cmder folder from ProgramFiles*86 to ProgramFiles folder everything just worked normally.

**Comment by daxgames** [comment]
The [Installation](https://github.com/cmderdev/cmder#installation) I nstructions recommend against putting Cmder in the `C:\program files*` folders.  There is user specific config in Cmder and thus the best and recommended place for it is in a folder inside a users home folder.

**Comment by vjeet911** [comment]
it solved for me by moving to "C:\program files " instead of "C:/Program Files(x86)"
