### ISSUE TITLE
[Bug] Clink git prompt shows ".invalid" as branch name in a git repo that uses reftables

### ISSUE THREAD

**Issue by chrisant996** [cmderdev/cmder#3057]
### Version Information

```markdown
Cmder version:  All versions.
```

### Cmder Edition

Cmder Full (with Git)

### Description of the issue

A breaking change in git has made it no longer possible to get the git branch name just by reading the HEAD file.  Now it's necessary to invoke git.exe.  In a git repo that uses the new reftable storage system, the HEAD file is hard-coded to say that the branch name is ".invalid".  So that's what shows up in the prompt.

### How to reproduce

1. Using the latest version of git
2. Run `git init test_repo && cd test_repo`
3. Verify that `git config extensions.refstorage` returns `reftable`
4. Observe the branch name is ".invalid" in Cmder

### Additional context

I submitted https://github.com/cmderdev/cmder/pull/3056 with changes that should fix the problem.

Please test and verify before approving the pull request.  I tested the changes with Cmder 1.3.25, but I may have missed something, or my testing might not have been sufficient for newer unreleased versions of Cmder.

### Checklist

- [x] I have read the documentation.
- [x] I have searched for similar issues and found none that describe my issue.
- [x] I have reproduced the issue on the latest version of Cmder.
- [x] I am certain my issues are not related to ConEmu, Clink, or other third-party tools that Cmder uses.

**Comment by chrisant996** [comment]
@daxgames @DRSDavidSoft this is a tracking issue for https://github.com/cmderdev/cmder/pull/3056 and the issue it's intended to fix.

**Comment by chrisant996** [comment]
This issue was resolved when #3056 was merged into master.

**Comment by mega5800** [comment]
Hi @chrisant996.

I'm using cmder and noticed that this issue still exists.
![image](https://github.com/user-attachments/assets/21e42c0c-1482-4fff-9881-505e067562ae)

I tried opening a new ticket using the GitHub app, as I don't have laptop access, but without any luck, that's why I'm replying to this thread.

Can you please investigate this issue and provide a solution?

Thank you.

**Comment by chrisant996** [comment]
It's fixed.

But that doesn't mean that Cmder has published a new version with the fix. 

Cmder hasn't published a new version in a few years.

**Comment by mega5800** [comment]
So, how can I get this fix?

Usually I run clink update to update cmder

**Comment by chrisant996** [comment]
It's not a Clink issue.  Updating Clink isn't related.

It's a Cmder issue, not a Clink issue.  I can't help with that end of things.

@daxgames @DRSDavidSoft this user is trying to figure out how to get a new version of Cmder that includes this fix.

<br/>

EDIT:

> Usually I run clink update to update cmder

No, that does not update Cmder.  It updates Clink.  Cmder bundles a copy of Clink, but Cmder contains more than just Clink itself.

**Comment by DRSDavidSoft** [comment]
@mega5800 We will make a new release soon -- also we need to provide a quick command to update **Cmder** as well, not just the clink component.

In the meantime, please go to the 📁 `vendor` inside your Cmder's root folder and **edit** the 📄 `clink.lua`, then replace the entire content with the fresh updated one from here:

https://github.com/cmderdev/cmder/blob/master/vendor/clink.lua

ℹ️ **Note:** You can also open this file using this command:
> `notepad.exe "%CMDER_ROOT%\vendor\clink.lua"`

This will update the affected file to fix the problem.

---

Please check for new Cmder releases a while later; the official update instructions is to extract a fresh compressed package on top of the current existing installation.

If you want to do that, you can download a fresh snapshot of the current branch using this guide:
1. Navigate to the [builds page](https://github.com/cmderdev/cmder/actions/workflows/build.yml?query=branch%3Amaster%20is%3Asuccess)
2. Open the first item in the list with the green checkmark (✅) before the title
3. Navigate to the **Artifacts** section, and download the relevant edition (`cmder.7z`, `cmder.zip`, `cmder_mini.zip`)
4. Extract on top of your existing installation

This will update **the entire** Cmder to the latest _unreleased builds_.

Lastly, apologies for the slow releases -- but we're coming up with some excellent additions to Cmder, and this fix was held back as we were working on the new branch.

Thank you, please let me know if this guide worked, and happy Cmdereeing 🥂

**Comment by chrisant996** [comment]
I should rephrase:

The `git` completions in Cmder come from the vladimir-kotikov/clink-completions repo.

If you're comfortable manually extracting files from that repo's zip file, then you could manually update those files under the Cmder install tree.

The git _prompt_ in Cmder is part of Cmder itself, and I think it still uses custom Lua code instead of using Clink's built in `git` Lua API functions.  If I'm remembering rightly then the git branch in the _prompt_ requires installing a pre-release build of Cmder, or manually modifying some of Cmder's Lua code, or using `clink config prompt use` to select a custom prompt instead of using Cmder's built-in prompt.

**Comment by mega5800** [comment]
Thank you @DRSDavidSoft for your message.

I was able to solve the issue by downloading an unreleased cmder version, now I can see the branch name correctly.
