### ISSUE TITLE
ls is not working correctly in cmder with unicode characters

### ISSUE THREAD

**Issue by DaZui** [cmderdev/cmder#918]
![image](https://cloud.githubusercontent.com/assets/5781966/14405204/095d2918-fe4f-11e5-9763-ae2964b397dd.png)

All chars with unicode filenames is replaced when testing ls.

![image](https://cloud.githubusercontent.com/assets/5781966/14405206/16ffd49e-fe4f-11e5-9d71-82a127d9e819.png)

When with "ls -b" it is like that.

The git-bash is good:
![image](https://cloud.githubusercontent.com/assets/5781966/14405210/3abc05b0-fe4f-11e5-95bc-ba3213d1711d.png)

**Comment by poychang** [comment]
#985

**Comment by poychang** [comment]
@DaZui This work #985 
`set LANG=zh_CN.UTF-8 ` for your cmder Environment

**Comment by mbirth** [comment]
And if that doesn't work, `set LANG=C.UTF-8` for generic UTF-8 support.

**Comment by tyler36** [comment]
@mbirth This worked for me.
```dir``` commands worked fine but the ```ls``` didn't until I ran this.
Add the line to my ```user-config.cmd``` file so it always runs

OS: Win10 Japanese

**Comment by 7dir** [comment]
my solution

```
set PATH=%ConEmuBaseDir%\Scripts;%PATH%
set LC_ALL=ru_RU.UTF-8
set LANG=ru_RU.UTF-8
chcp utf8
set ConEmuDefaultCp=65001
```

**Comment by marco-olimpio** [comment]
> Tks!!Work for me
> 
> In PT-BR words like 'Correção' showed: 'Correo' after use:
> 
> set LC_ALL=ru_RU.UTF-8
> set LANG=ru_RU.UTF-8
> chcp utf8
> set ConEmuDefaultCp=65001
> 
> It's work!

Man have you used ru_RU, not br_PT? Well... I've changed to br_PT ;) and it worked like a charm

set PATH=%ConEmuBaseDir%\Scripts;%PATH%
set LC_ALL=pt_BR.UTF-8
set LANG=pt_BR.UTF-8
chcp utf8
set ConEmuDefaultCp=65001

**Comment by daxgames** [comment]
Should be fixed in current version.  Closing.

**Comment by TomaszGrzmilas** [comment]
Still not working for polish.

'ls' above with wrong naming and 'dir' bellow (good)

![image](https://user-images.githubusercontent.com/32311696/58515167-4b551e80-81a4-11e9-9770-7c561718eb88.png)

**Comment by HenrykSz** [comment]
For polish. It works like a charm :)
set LC_ALL=pl_PL.UTF-8
set LANG=pl_PL.UTF-8
chcp utf8
set ConEmuDefaultCp=65001

**Comment by kiemrong08** [comment]
Thanks you , thank you, thank you
For Vietnamese. It work like a charm :))

```bash
chcp utf-8
set LC_ALL=en_US.UTF-8
set LANG=en_US.UTF-8
chcp utf8
set ConEmuDefaultCp=65001
```
