### ISSUE TITLE
Cannot save settings

### ISSUE THREAD

**Issue by denisz1** [cmderdev/cmder#936]
When I create a new task/shell group, and exit the app, it doesn't save.

My temp fix is to save the xml config elsewhere (use Export button). Close. Move that xml file over the real one. Then reopen cmder.

**Comment by iulo** [comment]
win10 same issue. solved with run cmder as admin.

**Comment by neilsimp1** [comment]
Win10 also, running as admin doesn't solve that for me. I'm on Insider Build 14342 if that makes any difference.

**Comment by Stanzilla** [comment]
Which dir are you running cmder from?

**Comment by neilsimp1** [comment]
Running as admin fixed it for me too.
Win10 Insider Preview
C:\Program Files\cmder\cmder.exe

**Comment by mrRosset** [comment]
It's normal starting from windows vista, programs need admin right to write into the programs files folders and that's where the config is. It would probably be easier to simply put cmder elsewhere (for example in the %localappdata% directory)

**Comment by denisz1** [comment]
Yes this is an admin rights issue.

**Comment by Goran7777** [comment]
Cant work from taskbar,must have a desktop icon to run as admin coz of save setting.

**Comment by iulo** [comment]
@Goran7777  
`settings` > `Startup` > `Tasks`  prepend a `*` in your default task command.
e.g. `*"C:\Program Files (x86)\Git\bin\sh.exe" --login -i`
They have a explain over the task textarea
